"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import AppShell from "@/components/workspace/AppShell";
import { apiGet, apiPost, apiPatch } from "@/lib/api";

export default function TeacherAssignments(){
 const params=useSearchParams(); const [courses,setCourses]=useState([]); const [selected,setSelected]=useState(""); const [assignments,setAssignments]=useState([]); const [form,setForm]=useState({title:"",description:"",dueAt:""}); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const c=await apiGet("/api/teacher/courses");setCourses(c||[]);setSelected(params.get("course")||c?.[0]?.id||"")}catch(e){setError(e.message)}})()},[params]);
 useEffect(()=>{if(!selected)return;(async()=>{try{setAssignments(await apiGet(`/api/teacher/courses/${selected}/assignments`)||[])}catch(e){setError(e.message)}})()},[selected]);
 async function create(e){e.preventDefault();if(!selected)return;try{await apiPost(`/api/teacher/courses/${selected}/assignments`,form);setForm({title:"",description:"",dueAt:""});setAssignments(await apiGet(`/api/teacher/courses/${selected}/assignments`)||[])}catch(e){setError(e.message)}}
 async function review(id){try{const data=await apiGet(`/api/teacher/assignments/${id}/submissions`);const text=data?.map(s=>`${s.student?.name||"Student"}: ${s.score??"Unscored"}`).join("\n")||"No submissions";alert(text)}catch(e){setError(e.message)}}
 return <AppShell role="TEACHER" title="Assignments" subtitle="Create work, review submissions and keep grading close to the classroom."><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><form onSubmit={create} className="rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[0.035]"><h2 className="font-semibold">Create assignment</h2><select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-4 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]"><option value="">Select course</option>{courses.map(c=><option value={c.id} key={c.id}>{c.code} — {c.title}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-3 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Assignment title" required/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-3 min-h-28 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Instructions"/><input type="datetime-local" value={form.dueAt?form.dueAt.slice(0,16):""} onChange={e=>setForm({...form,dueAt:e.target.value?`${e.target.value}:00Z`:""})} className="mt-3 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]"/><button className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-slate-900">Create assignment</button></form><div className="space-y-3">{assignments.map(a=><article key={a.id} className="rounded-2xl border bg-white p-5 dark:border-white/10 dark:bg-white/[0.035]"><div className="flex items-start justify-between"><div><h3 className="font-semibold">{a.title}</h3><p className="mt-1 text-sm text-slate-500">{a.description||"No instructions."}</p></div><span className="text-xs text-slate-400">{a.dueAt?new Date(a.dueAt).toLocaleDateString():"No due date"}</span></div><button onClick={()=>review(a.id)} className="mt-4 rounded-xl border px-3 py-2 text-xs font-medium">View submissions</button></article>)}{!assignments.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">No assignments for this course.</div>}</div></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</AppShell>;
}
