"use client";

import { useEffect, useState } from "react";
import AppShell from "@/components/workspace/AppShell";
import { apiGet, apiPost, apiPut, apiDelete } from "@/lib/api";

export default function TeacherClasses() {
  const [courses,setCourses]=useState<any[]>([]); const [form,setForm]=useState({code:"",title:"",description:""}); const [error,setError]=useState("");
  async function load(){try{setCourses(await apiGet("/api/teacher/courses")||[])}catch (e: any){setError(e.message)}} useEffect(()=>{load()},[]);
  async function create(e){e.preventDefault();try{await apiPost("/api/teacher/courses",form);setForm({code:"",title:"",description:""});load()}catch (e: any){setError(e.message)}}
  async function remove(id: any){if(!confirm("Delete this course?"))return;try{await apiDelete(`/api/teacher/courses/${id}`);load()}catch (e: any){setError(e.message)}}
  return <AppShell role="TEACHER" title="My classes" subtitle="Create and manage the courses you teach."><div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={create} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-white/[0.035]"><h2 className="font-semibold">Create a course</h2><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="mt-4 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Course code" required/><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-3 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Course title" required/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-3 min-h-28 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Description"/><button className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-slate-900">Create course</button></form><div className="space-y-3">{courses.map(c=><article key={c.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/[0.035]"><div className="flex justify-between gap-4"><div><div className="text-xs text-cyan-600 dark:text-cyan-300">{c.code}</div><h3 className="mt-1 font-semibold">{c.title}</h3><p className="mt-1 text-sm text-slate-500">{c.description||"No description."}</p></div><button onClick={()=>remove(c.id)} className="h-fit rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-600 dark:border-red-400/15 dark:text-red-300">Delete</button></div><div className="mt-4 flex gap-2"><a href={`/teacher/classes/${c.id}`} className="rounded-lg border px-3 py-1.5 text-xs">View class</a><a href={`/teacher/assignments?course=${c.id}`} className="rounded-lg border px-3 py-1.5 text-xs">Assignments</a></div></article>)}{!courses.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">No courses yet.</div>}</div></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</AppShell>;
}
