package com.codegrowth.service;

import com.codegrowth.entity.Competency;
import com.codegrowth.entity.CompetencyAssessment;
import com.codegrowth.entity.CompetencyAssessmentStatus;
import com.codegrowth.entity.CompetencyLevel;
import com.codegrowth.entity.Evaluation;
import com.codegrowth.entity.User;
import com.codegrowth.repository.CompetencyAssessmentRepository;
import com.codegrowth.repository.CompetencyRepository;
import com.codegrowth.repository.EvaluationRepository;
import com.codegrowth.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class CompetencyAssessmentService {

    private final CompetencyAssessmentRepository
            assessmentRepository;

    private final EvaluationRepository evaluationRepository;

    private final CompetencyRepository competencyRepository;

    private final UserRepository userRepository;

    public CompetencyAssessmentService(
            CompetencyAssessmentRepository assessmentRepository,
            EvaluationRepository evaluationRepository,
            CompetencyRepository competencyRepository,
            UserRepository userRepository) {

        this.assessmentRepository =
                assessmentRepository;

        this.evaluationRepository =
                evaluationRepository;

        this.competencyRepository =
                competencyRepository;

        this.userRepository =
                userRepository;
    }

    /*
     * Create a pending competency assessment.
     */
    public CompetencyAssessment createAssessment(
            Long evaluationId,
            Long competencyId) {

        Evaluation evaluation =
                evaluationRepository.findById(evaluationId)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Evaluation not found with id: "
                                                + evaluationId
                                )
                        );

        Competency competency =
                competencyRepository.findById(competencyId)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Competency not found with id: "
                                                + competencyId
                                )
                        );

        if (assessmentRepository
                .existsByEvaluationIdAndCompetencyId(
                        evaluationId,
                        competencyId)) {

            throw new IllegalArgumentException(
                    "This competency has already been assessed "
                            + "for this evaluation"
            );
        }

        /*
         * Student is obtained from:
         *
         * Evaluation
         *    ↓
         * Submission
         *    ↓
         * Student
         */
        User student =
                evaluation
                        .getSubmission()
                        .getStudent();

        CompetencyAssessment assessment =
                new CompetencyAssessment();

        assessment.setEvaluation(evaluation);
        assessment.setCompetency(competency);
        assessment.setStudent(student);

        assessment.setScore(0.0);

        assessment.setAssessedLevel(
                CompetencyLevel.BEGINNER
        );

        assessment.setStatus(
                CompetencyAssessmentStatus.PENDING
        );

        return assessmentRepository.save(
                assessment
        );
    }

    public List<CompetencyAssessment>
    getAllAssessments() {

        return assessmentRepository.findAll();
    }

    public Optional<CompetencyAssessment>
    getAssessmentById(Long id) {

        return assessmentRepository.findById(id);
    }

    public List<CompetencyAssessment>
    getAssessmentsByStudent(Long studentId) {

        return assessmentRepository
                .findByStudentId(studentId);
    }

    public List<CompetencyAssessment>
    getAssessmentsByCompetency(
            Long competencyId) {

        return assessmentRepository
                .findByCompetencyId(competencyId);
    }

    public List<CompetencyAssessment>
    getAssessmentsByEvaluation(
            Long evaluationId) {

        return assessmentRepository
                .findByEvaluationId(evaluationId);
    }

    public List<CompetencyAssessment>
    getAssessmentsByStatus(
            CompetencyAssessmentStatus status) {

        return assessmentRepository
                .findByStatus(status);
    }

    /*
     * Complete an assessment using the competency score
     * generated by the evaluation/AI engine.
     */
    public CompetencyAssessment assessCompetency(
            Long id,
            Double score,
            CompetencyLevel level,
            String evidence,
            String improvementSuggestion) {

        validateScore(score);

        CompetencyAssessment assessment =
                assessmentRepository.findById(id)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Competency assessment "
                                                + "not found with id: "
                                                + id
                                )
                        );

        assessment.setScore(score);

        assessment.setAssessedLevel(level);

        assessment.setEvidence(evidence);

        assessment.setImprovementSuggestion(
                improvementSuggestion
        );

        assessment.setStatus(
                CompetencyAssessmentStatus.ASSESSED
        );

        assessment.setAssessedAt(
                LocalDateTime.now()
        );

        return assessmentRepository.save(
                assessment
        );
    }

    /*
     * Verify an assessment.
     *
     * Later this can be restricted to teachers/admins
     * through authentication and authorization.
     */
    public CompetencyAssessment verifyAssessment(
            Long id) {

        CompetencyAssessment assessment =
                assessmentRepository.findById(id)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Competency assessment "
                                                + "not found with id: "
                                                + id
                                )
                        );

        if (assessment.getStatus()
                != CompetencyAssessmentStatus.ASSESSED) {

            throw new IllegalArgumentException(
                    "Only ASSESSED competency assessments "
                            + "can be verified"
            );
        }

        assessment.setStatus(
                CompetencyAssessmentStatus.VERIFIED
        );

        return assessmentRepository.save(
                assessment
        );
    }

    /*
     * Reject an assessment.
     */
    public CompetencyAssessment rejectAssessment(
            Long id) {

        CompetencyAssessment assessment =
                assessmentRepository.findById(id)
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Competency assessment "
                                                + "not found with id: "
                                                + id
                                )
                        );

        assessment.setStatus(
                CompetencyAssessmentStatus.REJECTED
        );

        return assessmentRepository.save(
                assessment
        );
    }

    private void validateScore(Double score) {

        if (score == null) {

            throw new IllegalArgumentException(
                    "Competency score cannot be null"
            );
        }

        if (score < 0 || score > 100) {

            throw new IllegalArgumentException(
                    "Competency score must be between 0 and 100"
            );
        }
    }

    public void deleteAssessment(Long id) {

        if (!assessmentRepository.existsById(id)) {

            throw new IllegalArgumentException(
                    "Competency assessment not found with id: "
                            + id
            );
        }

        assessmentRepository.deleteById(id);
    }
}