"use client";

import { useEffect, useState } from "react";
import AppShell from "@/components/workspace/AppShell";
import { apiGet, apiPost, apiPut } from "@/lib/api";

export default function StudentGoals() {
  const [goals, setGoals] = useState([]); const [form, setForm] = useState({ title: "", description: "", targetDate: "" }); const [error, setError] = useState("");
  async function load() { try { setGoals(await apiGet("/api/student/goals") || []); } catch (e) { setError(e.message); } }
  useEffect(() => { load(); }, []);
  async function create(e) { e.preventDefault(); try { await apiPost("/api/student/goals", form); setForm({ title: "", description: "", targetDate: "" }); load(); } catch (e) { setError(e.message); } }
  async function update(id, progress, status) { try { await apiPut(`/api/student/goals/${id}`, { progress: String(progress), status }); load(); } catch (e) { setError(e.message); } }
  return <AppShell role="STUDENT" title="Learning goals" subtitle="Set targets and keep progress visible." ><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><form onSubmit={create} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-white/[0.035]"><h2 className="font-semibold">Create a goal</h2><input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Goal title" required /><textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className="mt-3 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="What do you want to achieve?" /><input type="date" value={form.targetDate} onChange={(e)=>setForm({...form,targetDate:e.target.value ? `${e.target.value}T00:00:00Z` : ""})} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10 dark:bg-[#071018]" /><button className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-slate-900">Save goal</button></form><div className="space-y-3">{goals.map((g)=><article key={g.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/[0.035]"><div className="flex justify-between gap-4"><div><h3 className="font-semibold">{g.title}</h3><p className="mt-1 text-sm text-slate-500">{g.description || "No description."}</p></div><span className="text-xs text-slate-500">{g.status}</span></div><div className="mt-4 h-2 rounded-full bg-slate-100 dark:bg-white/[0.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:`${Math.min(100,Math.max(0,g.progress||0))}%`}} /></div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>{g.progress || 0}%</span><div className="flex gap-2"><button onClick={()=>update(g.id,Math.max(0,(g.progress||0)-10),g.status)} className="rounded-lg border px-2 py-1">−10</button><button onClick={()=>update(g.id,Math.min(100,(g.progress||0)+10),Math.min(100,(g.progress||0)+10)>=100?"COMPLETED":"ACTIVE")} className="rounded-lg border px-2 py-1">+10</button></div></div></article>)}{!goals.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">No goals yet.</div>}</div></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}</AppShell>;
}
