"use client";

import { useEffect, useState } from "react";
import AppShell from "@/components/workspace/AppShell";
import { apiGet, apiPost } from "@/lib/api";

export default function TeacherAnnouncements(){
 const [courses,setCourses]=useState([]);const [items,setItems]=useState([]);const [courseId,setCourseId]=useState("");const [form,setForm]=useState({title:"",message:""});const [error,setError]=useState("");
 async function load(){try{const [c,a]=await Promise.all([apiGet("/api/teacher/courses"),apiGet("/api/teacher/announcements")]);setCourses(c||[]);setItems(a||[]);if(!courseId)setCourseId(c?.[0]?.id||"")}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 async function publish(e){e.preventDefault();try{await apiPost(`/api/teacher/courses/${courseId}/announcements`,form);setForm({title:"",message:""});load()}catch(e){setError(e.message)}}
 return <AppShell role="TEACHER" title="Announcements" subtitle="Communicate important updates to your learners."><div className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><form onSubmit={publish} className="rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[0.035]"><h2 className="font-semibold">Publish update</h2><select value={courseId} onChange={e=>setCourseId(e.target.value)} className="mt-4 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]"><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.title}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-3 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Title" required/><textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className="mt-3 min-h-36 w-full rounded-xl border p-3 text-sm dark:border-white/10 dark:bg-[#071018]" placeholder="Message" required/><button className="mt-4 w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-slate-900">Publish</button></form><div className="space-y-3">{items.map(a=><article key={a.id} className="rounded-2xl border bg-white p-5 dark:border-white/10 dark:bg-white/[0.035]"><div className="text-xs text-cyan-600 dark:text-cyan-300">{a.course?.code||"Course"}</div><h3 className="mt-1 font-semibold">{a.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{a.message}</p><div className="mt-3 text-[11px] text-slate-400">{a.createdAt?new Date(a.createdAt).toLocaleString():""}</div></article>)}{!items.length&&<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">No announcements yet.</div>}</div></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</AppShell>;
}
